### ISSUE TITLE
复制出现错误

### ISSUE THREAD

**Issue by pengxy0** [Yaozhuwa/AttachFlow#16]
在复制图片之后，右上角显示已复制到粘贴板，但是随后又显示下图，而且也粘贴不上。大佬帮忙看看咋回事情嘞
![image](https://github.com/Yaozhuwa/AttachFlow/assets/130196652/d416aed5-3bb9-4379-8e8d-971aea3b6025)

**Comment by Yaozhuwa** [comment]
你是复制所有图片/附件都会失效，还是某个图片失效。

最好再提供下复制的图片链接的文本内容

**Comment by pengxy0** [comment]
@Yaozhuwa 是所有的图片都会失效，这个是某个图片的文本：![\<img alt="" data-attachment-key="9W47TLIK" width="214" height="184" src="attachments/9W47TLIK.png" ztype="zimage">](attachments/9W47TLIK.png)

**Comment by Yaozhuwa** [comment]
> @Yaozhuwa 是所有的图片都会失效，这个是某个图片的文本：![<img alt="" data-attachment-key="9W47TLIK" width="214" height="184" src="attachments/9W47TLIK.png" ztype="zimage">](attachments/9W47TLIK.png)

你把[]内的文字删掉试下有用吗

**Comment by Yaozhuwa** [comment]
你是用 HTML 语法嵌入的图片？

**Comment by pengxy0** [comment]
这样可以不？
![recording](https://github.com/Yaozhuwa/AttachFlow/assets/130196652/7d396636-6b65-4041-a49d-83b668151c33)

**Comment by Yaozhuwa** [comment]
<img width="331" alt="image" src="https://github.com/Yaozhuwa/AttachFlow/assets/28787183/68ada5ff-61b0-4317-b961-5c74d26a70c0">

你的文件夹路径包含了一个`'`号，导致调用系统命令时出错

**Comment by Yaozhuwa** [comment]
下个版本会更新这个修复，到时候直接更新就行
