### ISSUE TITLE
右键菜单新增关于附件的文件移动。

### ISSUE THREAD

**Issue by MoCur** [Yaozhuwa/AttachFlow#2]
希望可以添加一个新功能。
就是使用右键菜单时，通过填写路径，可以对该附件进行文件移动。

**Comment by MoCur** [comment]
同时也希望右键菜单的删除文件，可以往下放一些。
放在首位，很怕有时候会误触.......

**Comment by Yaozhuwa** [comment]
> 希望可以添加一个新功能。 就是使用右键菜单时，通过填写路径，可以对该附件进行文件移动。

之后有空应该会加上~


> 同时也希望右键菜单的删除文件，可以往下放一些。 放在首位，很怕有时候会误触.......

有道理

**Comment by AiurArtanis** [comment]
+1
不过我比较希望的实现方式是通过调用ob自带的移动，这样可以弹出窗口输入带提示的路径以实现移动

**Comment by Yaozhuwa** [comment]
> 不过我比较希望的实现方式是通过调用ob自带的移动，这样可以弹出窗口输入带提示的路径以实现移动

Obsidian API 没有提供自带的移动功能，我仿制了一个，效果基本上一模一样。更新0.4.3版本即可
