### ISSUE TITLE
【Feature】图床图片增强

### ISSUE THREAD

**Issue by likemuuxi** [Yaozhuwa/AttachFlow#4]
如题

**Comment by likemuuxi** [comment]
图床链接图片，在阅读模式下会显示出拖拽图标和外层方框

**Comment by Yaozhuwa** [comment]
v0.4.0 支持了外链图片的右键菜单~

> 图床链接图片，在阅读模式下会显示出拖拽图标和外层方框

更新到最新版本

**Comment by likemuuxi** [comment]
右键菜单弹出后立刻消失

**Comment by Yaozhuwa** [comment]
> 右键菜单弹出后立刻消失

能具体点吗，或者提供录屏。我的本地Mac和WINDOWS环境下均没有这种问题~

**Comment by likemuuxi** [comment]
好了  应该是有冲突了
