### ISSUE TITLE
[feature] 给一个选项关闭全屏显示图片

### ISSUE THREAD

**Issue by panwanke** [Yaozhuwa/AttachFlow#6]
很感谢作者最近更新了全屏显示图片功能。但我在使用过程遇到一些问题：
- 在没有开启drag to resize的情况下，不能直接全屏显示图片
- 即使开启 drag to resize，全屏显示的识别范围存在问题，即需要将鼠标移动到图片特定位置才能进行点击
- 右键只能恢复全屏显示，不能进行复制；不能拖动图片位置。这使得功能没有 image toolkit 健全。此外，该功能和 image toolkit 会有点冲突，一般来说会优先使用 image toolkit 的图片悬浮功能，然后再点击图片会全屏显示。

鉴于此，一些小建议：
- 增加一个选项关闭全屏显示图片
- 或者完全借鉴  image toolkit  的功能

**Comment by Yaozhuwa** [comment]
> 在没有开启drag to resize的情况下，不能直接全屏显示图片
> 即使开启 drag to resize，全屏显示的识别范围存在问题，即需要将鼠标移动到图片特定位置才能进行点击

1. 在没有开启drag to resize的情况下，也可以点击查看大图，需要点击图像右半边
2. 全屏显示的识别范围我设置的就是点击图像右半边，请看更新日志

> 右键只能恢复全屏显示，不能进行复制；不能拖动图片位置。这使得功能没有 image toolkit 健全。此外，该功能和 image toolkit 会有点冲突，一般来说会优先使用 image toolkit 的图片悬浮功能，然后再点击图片会全屏显示。
> 鉴于此，一些小建议：
> 增加一个选项关闭全屏显示图片
> 或者完全借鉴 image toolkit 的功能

开关选项会马上加上，其他的慢慢优化吧

**Comment by Yaozhuwa** [comment]
0.3.1 版本拖拽调整大小不再会触发 Image Toolkit 的大图查看了。

目前本插件的点击查看大图功能还比较粗糙，用的不爽可以先用 Image Toolkit.
