### ISSUE TITLE
想要调整图片大小，点击就会放大图片怎么办

### ISSUE THREAD

**Issue by Chentongda** [Yaozhuwa/AttachFlow#7]
<img width="1623" alt="image" src="https://github.com/Yaozhuwa/AttachFlow/assets/48764946/d65b87b3-7df5-4ac0-a889-4967cdf7133e">

**Comment by Yaozhuwa** [comment]
光标在图片边缘不会点击放大，可以按住左键拖拽
<img width="389" alt="image" src="https://github.com/Yaozhuwa/AttachFlow/assets/28787183/7a86c531-8d9b-4080-9766-40606066d9d7">

**Comment by Yaozhuwa** [comment]
插件设置中还需要打开拖拽调整大小的开关

**Comment by yoghurtlee-thu** [comment]
+1。在试图拖拽放大/缩小图片的时候经常会直接放大，来不及进行拖拽。希望开发大大能修一下，改成拖拽的时候只改变大小而不放大。

我这边似乎只是这几天出现的问题，电脑系统是 macOS Sonoma，Obsidian 是 1.5.12，插件版本是 0.3.1

**Comment by Yaozhuwa** [comment]
> +1。在试图拖拽放大/缩小图片的时候经常会直接放大，来不及进行拖拽。希望开发大大能修一下，改成拖拽的时候只改变大小而不放大。
> 
> 我这边似乎只是这几天出现的问题，电脑系统是 macOS Sonoma，Obsidian 是 1.5.12，插件版本是 0.3.1

拖拽时是需要按住鼠标左键不放时拖动，0.3.1版本已经不会触发放大，可以检查下自己鼠标是否电量不足导致按住左键有时会断续的问题 @yoghurtlee-thu

**Comment by yoghurtlee-thu** [comment]
> > +1。在试图拖拽放大/缩小图片的时候经常会直接放大，来不及进行拖拽。希望开发大大能修一下，改成拖拽的时候只改变大小而不放大。
> > 我这边似乎只是这几天出现的问题，电脑系统是 macOS Sonoma，Obsidian 是 1.5.12，插件版本是 0.3.1
> 
> 拖拽时是需要按住鼠标左键不放时拖动，0.3.1版本已经不会触发放大，可以检查下自己鼠标是否电量不足导致按住左键有时会断续的问题 @yoghurtlee-thu

emmm，这边用的是 MacBook 的触控板，这几天几乎就没有成功缩放过（）不过图床图片是可以正常缩放的。

**Comment by Yaozhuwa** [comment]
> emmm，这边用的是 MacBook 的触控板，这几天几乎就没有成功缩放过（）不过图床图片是可以正常缩放的。

能录屏吗，我看下

**Comment by yoghurtlee-thu** [comment]
> > emmm，这边用的是 MacBook 的触控板，这几天几乎就没有成功缩放过（）不过图床图片是可以正常缩放的。
> 
> 能录屏吗，我看下


https://github.com/Yaozhuwa/AttachFlow/assets/146422759/3ed0fc13-5592-49eb-a608-36bf9f4918d6

**Comment by Yaozhuwa** [comment]
> > > emmm，这边用的是 MacBook 的触控板，这几天几乎就没有成功缩放过（）不过图床图片是可以正常缩放的。
> > 
> > 
> > 能录屏吗，我看下
> 
>  Longshot-20240415133727.mov

你自己的主题或者CSS自带了点击查看大图的功能，与本插件冲突了，你需要关闭主题的该功能或者对应的CSS片段

**Comment by yoghurtlee-thu** [comment]
> > > > emmm，这边用的是 MacBook 的触控板，这几天几乎就没有成功缩放过（）不过图床图片是可以正常缩放的。
> > > 
> > > 
> > > 能录屏吗，我看下
> > 
> > 
> > Longshot-20240415133727.mov
> 
> 你自己的主题或者CSS自带了点击查看大图的功能，与本插件冲突了，你需要关闭主题的该功能或者对应的CSS片段
> 
> 如果是Minimal主题，StyleSettings 打开如下选项： <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/28787183/322542565-58c274a4-088b-4b47-8ffa-fddd753b1522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMjY3NjQsIm5iZiI6MTcxMzIyNjQ2NCwicGF0aCI6Ii8yODc4NzE4My8zMjI1NDI1NjUtNThjMjc0YTQtMDg4Yi00YjQ3LThmZmEtZmRkZDc1M2IxNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDAwMTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNjQ3Yjg4YTM0MTIxOTVlMWQ3MzIxZTM2YzQ0NWY4NzYyNmI4NzIzYTM3ZTYwYzA2YTZmOGIwMjg0ZTIzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VKFktIqCTZoH9B46V1tn326CoxxtGwTXL0TACC8SZc4">

确实是这样，感谢大佬！
