### ISSUE TITLE
最新的点击查看大图功能，默认大小100%会太大了

### ISSUE THREAD

**Issue by calmwaves111** [Yaozhuwa/AttachFlow#8]
能否增加可选项，可选关闭这个功能呢

因为我之前一直用的是[image toolkit](https://github.com/sissilab/obsidian-image-toolkit)插件来查看大图，它会在点击查看时自适应屏幕大小，把全图展示出来，而现在用这个插件，会直接显示100%大小，我很多图片都太大了，点开看显示不全

另外[image toolkit](https://github.com/sissilab/obsidian-image-toolkit)插件功能很多，我也一直在用，而目前attachflow插件的功能没有image toolkit多，所以我仍旧希望用image toolkit插件来查看大图，所以希望能选择关闭这个功能，就和这个拖拽调节图片大小一样
（拖拽功能很厉害，不过我的笔记不排版，直接把图片全都用css设成20%大小，然后通过image toolkit插件点开查看，所以我用不上关掉了）

![image](https://github.com/Yaozhuwa/AttachFlow/assets/56907077/31b86e57-a8c7-4e1b-97f1-8303f2ccc142)

**Comment by Yaozhuwa** [comment]
> 能否增加可选项，可选关闭这个功能呢
> 因为我之前一直用的是[image toolkit](https://github.com/sissilab/obsidian-image-toolkit)插件来查看大图，它会在点击查看时自适应屏幕大小，把全图展示出来，而现在用这个插件，会直接显示100%大小，我很多图片都太大了，点开看显示不全

会增加开关的，图片过大的确需要自适应大小显示全图

**Comment by Yaozhuwa** [comment]
0.3.1 版本拖拽调整大小不再会触发 Image Toolkit 的大图查看了。

目前本插件的点击查看大图功能还比较粗糙，用的不爽可以先用 Image Toolkit.

**Comment by jianwu003** [comment]
> 0.3.1 版本拖拽调整大小不再会触发 Image Toolkit 的大图查看了。
> 
> 目前本插件的点击查看大图功能还比较粗糙，用的不爽可以先用 Image Toolkit.

亲爱的开发者，将这个 img 标签的缩放单位改为百分比就能适应整个屏幕了，而不是图片的像素值，在滚动的时候，有显示百分比，所以我觉得这个对您不难实现
![image](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/54981d05-39e5-4240-9d06-7d36f6d58ef5)

**Comment by jianwu003** [comment]
我优化了这个功能，同时增加了可设置的初始值
![image](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/953d6ea7-3818-49ba-b6fc-271a970c03bb)

![image](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/feb13216-b406-4c09-a4a5-6b443e7f4875)


插件包：
https://wwt.lanzouq.com/i4ne81uo2hgb
密码:b4on

源码：
https://wwt.lanzouq.com/iPuKM1uo2hhc
密码:7gbu

另外，需要在 css 里面加上
```css
/* Fixed 图片先放大在缩小造成的视觉卡顿 */
img#af-zoomed-image {
    width: 0;
    height: 0;
}
```

**Comment by jianwu003** [comment]
另外，反馈一个插件的 BUG，即：
当插件启动之后第一次点击的图片，其宽度的变化比较卡顿，但是之后的点击不会，演示的是未经过修改的版本，gif 帧率比较低，第二次其实是很顺滑的

![PixPin_2024-04-11_14-34-50](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/6b42d85a-690c-4da4-8e17-fdc7806699e3)

**Comment by Yaozhuwa** [comment]
v0.3.2 版本大图显示超出屏幕时将自适应为75%屏幕大小显示

> 另外，反馈一个插件的 BUG，即：
> 当插件启动之后第一次点击的图片，其宽度的变化比较卡顿，但是之后的点击不会，演示的是未经过修改的版本，gif 帧率比较低，第二次其实是很顺滑的

我感觉不出来啊，你懂代码的话知道是什么原因吗

**Comment by jianwu003** [comment]
> v0.3.2 版本大图显示超出屏幕时将自适应为75%屏幕大小显示
> 
> > 另外，反馈一个插件的 BUG，即：
> > 当插件启动之后第一次点击的图片，其宽度的变化比较卡顿，但是之后的点击不会，演示的是未经过修改的版本，gif 帧率比较低，第二次其实是很顺滑的
> 
> 我感觉不出来啊，你懂代码的话知道是什么原因吗 @jianwu003

很可能是渲染的问题，之前弄插件的时候遇到过不加这个会卡顿（用到了 top left 定位，用tansform 则不加这个也没事，但是transform会造成盒子的微小挤压），这个就几行代码就行
https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestAnimationFrame

**Comment by jianwu003** [comment]
在 0.3.1 版本中，加入如下 css 测试，在 0.4.0 版本中，height 和 width 的大小在没有缩放的情况下没有注入到 style 里面，所以动画无法生效，不排除是程序有影响性能的bug，所以作者可以在最新版加入 js 控制的 width 和 height 测试一下，加动画是为了测试图片放大过程中残影问题，深色模式下用亮色图片测试，或相反（在链接中有视频）。

图片残影问题：点击图片放大，图片是先保持原始值，后续用 js 缩小，当 js 有一定延迟时，留下一段残影
解决办法：用 css 或 js 设定 width 和 height 的初始值为 0，然后进行放大
```css
img#af-zoomed-image {
	width: 0;
    height: 0;
	transition: all 1s ease-in-out;
}
```
BUG 视频
https://wwt.lanzouq.com/i1gA31va9xfa
密码:g2kq

**Comment by jianwu003** [comment]
目前没有问题了，作者辛苦了

> @jianwu003 我更新了 0.4.1 版本，你试下还有问题吗？

**Comment by Yaozhuwa** [comment]
> 目前上面的没有问题了，作者辛苦了。不过网络图片拖拽不会实际不会更新, 猜测是对正则处理的问题，可能有的图片没有图片格式，被识别成其他链接，作者可以试着直接排除链接里面的 .md，而不是单独匹配图片格式，下面是我之前用过的匹配图片的正则
> 
> ```ts
> let regexImg = new RegExp('!\\[(?!.*\\.md)(.*?)\\]\\(.*?\\)|!\\[\\[(?!.*\\.md)(.*?)\\]\\]');
> ```
> 
> ```ts
> // 匹配 Markdown 图片和 WiKi 图片，md 图片优先本地
> let regexImg = new RegExp('!\\[.*?\\]\\((.*?(\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp|\\.raw|\\.svg).*?)\\)|!\\[\\[(.*?(http|\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp|\\.raw|\\.svg).*?)\\]\\]|!\\[.*\\]\\(http.*\\)');
> ```
> 
> `![]( https://ts1.cn.mm.bing.net/th/id/R-C.748160bf925a7acb3ba1c9514bbc60db?rik=AYY%2bJ9WcXYIMgw&riu=http%3a%2f%2fseopic.699pic.com%2fphoto%2f50017%2f0822.jpg_wh1200.jpg&ehk=CMVcdZMU6xxsjVjafO70cFcmJvD62suFC1ytk8UuAUk%3d&risl=&pid=ImgRaw&r=0 )`
> 
> > @jianwu003 我更新了 0.4.1 版本，你试下还有问题吗？

这个图片链接的前后多了空格，导致识别失败了，把空格删掉就好了，后续我看下支持空格。。

**Comment by jianwu003** [comment]
> > 目前上面的没有问题了，作者辛苦了。不过网络图片拖拽不会实际不会更新, 猜测是对正则处理的问题，可能有的图片没有图片格式，被识别成其他链接，作者可以试着直接排除链接里面的 .md，而不是单独匹配图片格式，下面是我之前用过的匹配图片的正则
> > ```ts
> > let regexImg = new RegExp('!\\[(?!.*\\.md)(.*?)\\]\\(.*?\\)|!\\[\\[(?!.*\\.md)(.*?)\\]\\]');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ts
> > // 匹配 Markdown 图片和 WiKi 图片，md 图片优先本地
> > let regexImg = new RegExp('!\\[.*?\\]\\((.*?(\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp|\\.raw|\\.svg).*?)\\)|!\\[\\[(.*?(http|\\.jpg|\\.jpeg|\\.png|\\.gif|\\.bmp|\\.webp|\\.raw|\\.svg).*?)\\]\\]|!\\[.*\\]\\(http.*\\)');
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `![]( https://ts1.cn.mm.bing.net/th/id/R-C.748160bf925a7acb3ba1c9514bbc60db?rik=AYY%2bJ9WcXYIMgw&riu=http%3a%2f%2fseopic.699pic.com%2fphoto%2f50017%2f0822.jpg_wh1200.jpg&ehk=CMVcdZMU6xxsjVjafO70cFcmJvD62suFC1ytk8UuAUk%3d&risl=&pid=ImgRaw&r=0 )`
> > > @jianwu003 我更新了 0.4.1 版本，你试下还有问题吗？
> 
> 这个图片链接的前后多了空格，导致识别失败了，把空格删掉就好了，后续我看下支持空格。。 [a17ef25](https://github.com/Yaozhuwa/AttachFlow/commit/a17ef2599cf8f04a9f44ea0fc1a1d0305857181e) 这个 commit 修复了该问题，下次更新会解决~

作者看一下这个链接，没有空格，也不行，那个空格是用您的另一个插件自动化生成的，这个没有空格，但是有英文的 )，也不行，我上面第二个正则表达式可以正确在folder note识别这个
`![](https://cubox.pro/c/filters:no_upscale()?imageUrl=https%3A%2F%2Fmmbiz.qpic.cn%2Fmmbiz_png%2FpKdCMcjAEORUEYuETgOUSwGvY0ic9ojxib9x34haYO4YxmcibQibt8MeiaDcMOicJhGw29zkvUHibxFean5Rd2mSD83RA%2F640%3Fwx_fmt%3Dpng&valid=true)`

**Comment by Yaozhuwa** [comment]
https://github.com/Yaozhuwa/AttachFlow/commit/65c0c6d9aef0b731cbcabf1bd98ec3402af1707a 能识别括号了，下个版本更新，可以暂时用下面的 main.js 试用
https://musetransfer.com/s/m4wnwisqm 请点击链接获取《修复Markdown外链识别》, 有效期至4月25日

> 那个空格是用您的另一个插件自动化生成的

这个空格是什么情况下生成的，我自己无法复现~

**Comment by jianwu003** [comment]
先() ，然后再最前面加 `![]` , 第一张图。另外 
- Easy Typing 有时会将 `![]()` 里面的 png 格式化成 `. Png` , （忘了是在什么情况下出现的，作者等之后我复现了再说，我可以用正则排除，只是可能是个 bug）
- 第二个是 Easy Typing 的 ctrl + shift + v 失效，逻辑上来说是应该无格式化粘贴之后不进行格式化处理，看第二张 gif，配置在最后面（快捷键无冲突）


![空格](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/b0e4e975-b95b-4090-9f5d-1df8e8b4a514)
![20240418_092942](https://github.com/Yaozhuwa/AttachFlow/assets/159551078/d3f6dbf4-feaa-43e0-95a4-4319af2212ce)

[data.json](https://github.com/Yaozhuwa/AttachFlow/files/15018836/data.json)

**Comment by Yaozhuwa** [comment]
> 先() ，然后再最前面加 `![]` , 第一张图。另外
> 
> * Easy Typing 有时会将 `![]()` 里面的 png 格式化成 `. Png` , （忘了是在什么情况下出现的，作者等之后我复现了再说，我可以用正则排除，只是可能是个 bug）
> * 第二个是 Easy Typing 的 ctrl + shift + v 失效，逻辑上来说是应该无格式化粘贴之后不进行格式化处理，看第二张 gif，配置在最后面（快捷键无冲突）

0. 先（）在加前面的，加空格是因为你自定义正则的规则，改成 (file:///|https?://|ftp://|obsidian://|zotero://|www.)[^\s（）《》。,，！？;；：“”‘’\)\(\[\]\{\}']+|-- 就好了。

2. Ctrl+Shift+V 失效在v5.3.0版本特地修复了，你更新下插件试试~

**Comment by jianwu003** [comment]
好了，感谢作者，那个自定义正则还以为是插件自带的，ctrl + shift + v 已经好了，辛苦作者了

**Comment by bingtuzibb** [comment]
鼠标拖拉缩放图片，最小只能缩放到100，把这个限制去掉吗，可以缩的更小一点
