### ISSUE TITLE
0.2.5 会与image toolkit 产生冲突

### ISSUE THREAD

**Issue by lijkop** [Yaozhuwa/AttachFlow#9]
-  当调节图片的大小之后，会自动调用image toolkit 打开图片。

*  0.3最新版本 点击图片时图片显示的大小 太大了，每次必须手动缩小图片

*

**Comment by Yaozhuwa** [comment]
0.3.1 版本拖拽调整大小不再会触发 Image Toolkit 的大图查看了。

目前本插件的点击查看大图功能还比较粗糙，用的不爽可以先用 Image Toolkit.

**Comment by Yaozhuwa** [comment]
0.3.2版本优化了点击查看大图的功能，应该还凑合了~
